title = 'My New Hugo Site'
defaultContentLanguage = "de-DE"

[languages]
    [languages.de-DE]
        languageCode = 'de-DE'
        languageDirection = 'ltr'
        languageName = 'Deutsch'
        title = 'Projekt Dokumentation'
        weight = 1
        baseURL = "https://example.de"

    [languages.en-US]
        languageCode = 'en-US'
        languageDirection = 'ltr'
        languageName = 'English'
        title = 'Project Documentation'
        weight = 2
        baseURL = "https://example.com"